# Generated by Django 4.2.6 on 2024-03-02 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('broker_name', models.CharField(max_length=255)),
                ('trading_platform', models.CharField(max_length=255)),
                ('logging_id', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('totp_key', models.CharField(max_length=255)),
                ('fa_pin', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=15)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('enctoken', models.TextField()),
                ('active_api', models.BooleanField(default=False)),
                ('advance_totp_security', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
